// Mocks generated by Mockito 5.4.6 from annotations
// in typed_cached_query/test/src/integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;

import '../data/models/create_user_request.dart' as _i6;
import '../data/models/mock_api_service.dart' as _i4;
import '../data/models/page_args.dart' as _i8;
import '../data/models/paged_response.dart' as _i3;
import '../data/models/update_user_request.dart' as _i7;
import '../data/models/user.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePagedResponse_1 extends _i1.SmartFake implements _i3.PagedResponse {
  _FakePagedResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MockApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockApiService extends _i1.Mock implements _i4.MockApiService {
  MockMockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.User> getUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [id]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getUser, [id])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<List<_i2.User>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i5.Future<List<_i2.User>>.value(<_i2.User>[]),
          )
          as _i5.Future<List<_i2.User>>);

  @override
  _i5.Future<_i2.User> createUser(_i6.CreateUserRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [request]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#createUser, [request])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User> updateUser(_i7.UpdateUserRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [request]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#updateUser, [request])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<void> deleteUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.PagedResponse> getUsersPage(_i8.PageArgs? args) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersPage, [args]),
            returnValue: _i5.Future<_i3.PagedResponse>.value(
              _FakePagedResponse_1(
                this,
                Invocation.method(#getUsersPage, [args]),
              ),
            ),
          )
          as _i5.Future<_i3.PagedResponse>);
}
