// Mocks generated by Mockito 5.4.6 from annotations
// in typed_cached_query/test/mutation_key_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import '../../../src/models/mutation_key_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [MockApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockApiService extends _i1.Mock implements _i2.MockApiService {
  MockMockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.User> createUser(_i2.CreateUserRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [request]),
            returnValue: _i3.Future<_i2.User>.value(_FakeUser_0(this, Invocation.method(#createUser, [request]))),
          )
          as _i3.Future<_i2.User>);

  @override
  _i3.Future<_i2.User> updateUser(_i2.UpdateUserRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [request]),
            returnValue: _i3.Future<_i2.User>.value(_FakeUser_0(this, Invocation.method(#updateUser, [request]))),
          )
          as _i3.Future<_i2.User>);

  @override
  _i3.Future<void> deleteUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
